import type { Dish } from "@/types";

export const initialDishes: Dish[] = [
  {
    id: 1,
    name: "Classic Margherita Pizza",
    price: 499,
    description: "Traditional pizza with San Marzano tomatoes, fresh mozzarella, basil, salt, and extra-virgin olive oil. Contains gluten and dairy.",
    image: "https://picsum.photos/id/42/600/400",
  },
  {
    id: 2,
    name: "Grilled Salmon Salad",
    price: 899,
    description: "A healthy salad with grilled salmon, mixed greens, cherry tomatoes, and a lemon-dill vinaigrette. Naturally gluten-free.",
    image: "https://picsum.photos/id/338/600/400",
  },
  {
    id: 3,
    name: "Spaghetti Carbonara",
    price: 650,
    description: "A classic Roman pasta dish with egg, pecorino cheese, guanciale (cured pork jowl), and black pepper. Contains gluten, dairy, and pork.",
    image: "https://picsum.photos/id/202/600/400",
  },
  {
    id: 4,
    name: "Vegan Lentil Soup",
    price: 350,
    description: "A hearty and nutritious soup made with green lentils, carrots, celery, and onions. Completely plant-based and gluten-free.",
    image: "https://picsum.photos/id/206/600/400",
  },
  {
    id: 5,
    name: "Chicken Pad Thai",
    price: 575,
    description: "Stir-fried rice noodles with chicken, tofu, peanuts, scrambled egg, and bean sprouts in a tamarind sauce. Contains nuts, egg, and soy.",
    image: "https://picsum.photos/id/24/600/400",
  },
  {
    id: 6,
    name: "Veg Burger",
    price: 550,
    description: "Juicy Veg patty on a brioche bun with lettuce, tomato, and our special sauce. Served with fries. Contains gluten and dairy (in bun and sauce).",
    image: "https://picsum.photos/id/835/600/400",
  },
  {
    id: 7,
    name: "Mushroom Risotto",
    price: 675,
    description: "Creamy risotto cooked with a mix of wild mushrooms, Parmesan cheese, and white wine. Contains dairy. Can be made vegan upon request.",
    image: "https://picsum.photos/id/292/600/400",
  },
  {
    id: 8,
    name: "Almond Croissant",
    price: 250,
    description: "A flaky, buttery croissant filled with a sweet almond paste and topped with sliced almonds and powdered sugar. Contains gluten, dairy, and nuts.",
    image: "https://picsum.photos/id/326/600/400",
  },
  {
    id: 9,
    name: "Butter Chicken",
    price: 550,
    description: "Tender chicken in a mildly spiced, creamy tomato sauce. Served with basmati rice and naan bread. Contains dairy and gluten (naan).",
    image: "https://picsum.photos/id/962/600/400",
  },
  {
    id: 10,
    name: "Sushi Platter",
    price: 1200,
    description: "A selection of fresh nigiri and maki rolls, including tuna, salmon, and California rolls. Served with soy sauce, wasabi, and pickled ginger. Contains fish and soy.",
    image: "https://picsum.photos/id/30/600/400",
  },
  {
    id: 11,
    name: "Ribeye Steak",
    price: 1500,
    description: "A 12oz ribeye steak cooked to your liking, served with garlic mashed potatoes and seasonal vegetables. Gluten-free.",
    image: "https://picsum.photos/id/83/600/400",
  },
  {
    id: 12,
    name: "Chocolate Lava Cake",
    price: 375,
    description: "Warm chocolate cake with a gooey molten center, served with a scoop of vanilla bean ice cream. Contains gluten and dairy.",
    image: "https://picsum.photos/id/211/600/400",
  },
  {
    id: 13,
    name: "Chicken Tikka Masala",
    price: 525,
    description: "Chunks of roasted marinated chicken in a spiced curry sauce. The sauce is usually creamy and orange-coloured. Contains dairy.",
    image: "https://picsum.photos/id/992/600/400",
  },
  {
    id: 14,
    name: "Paneer Butter Masala",
    price: 475,
    description: "A rich and creamy dish of paneer (Indian cheese) in a tomato, butter and cashew sauce. Vegetarian. Contains dairy and nuts.",
    image: "https://picsum.photos/id/1060/600/400",
  },
  {
    id: 15,
    name: "Vegetable Samosas",
    price: 180,
    description: "Crispy pastry filled with spiced potatoes and peas, served with a tamarind chutney. Vegan. Contains gluten.",
    image: "https://picsum.photos/id/493/600/400",
  },
  {
    id: 16,
    name: "Garlic Naan",
    price: 90,
    description: "Soft, leavened flatbread baked in a tandoor oven and brushed with garlic butter. Vegetarian. Contains gluten and dairy.",
    image: "https://picsum.photos/id/450/600/400",
  },
  {
    id: 17,
    name: "Classic Margherita Pizza",
    price: 499,
    description: "Traditional pizza with San Marzano tomatoes, fresh mozzarella, basil, salt, and extra-virgin olive oil. Contains gluten and dairy.",
    image: "https://picsum.photos/id/42/600/400",
  },
  {
    id: 18,
    name: "Grilled Salmon Salad",
    price: 899,
    description: "A healthy salad with grilled salmon, mixed greens, cherry tomatoes, and a lemon-dill vinaigrette. Naturally gluten-free.",
    image: "https://picsum.photos/id/338/600/400",
  },
  {
    id: 19,
    name: "Spaghetti Carbonara",
    price: 650,
    description: "A classic Roman pasta dish with egg, pecorino cheese, guanciale (cured pork jowl), and black pepper. Contains gluten, dairy, and pork.",
    image: "https://picsum.photos/id/202/600/400",
  },
  {
    id: 20,
    name: "Vegan Lentil Soup",
    price: 350,
    description: "A hearty and nutritious soup made with green lentils, carrots, celery, and onions. Completely plant-based and gluten-free.",
    image: "https://picsum.photos/id/206/600/400",
  },
  {
    id: 21,
    name: "Chicken Pad Thai",
    price: 575,
    description: "Stir-fried rice noodles with chicken, tofu, peanuts, scrambled egg, and bean sprouts in a tamarind sauce. Contains nuts, egg, and soy.",
    image: "https://picsum.photos/id/24/600/400",
  },
  {
    id: 22,
    name: "Beef Burger",
    price: 550,
    description: "Juicy beef patty on a brioche bun with lettuce, tomato, and our special sauce. Served with fries. Contains gluten and dairy (in bun and sauce).",
    image: "https://picsum.photos/id/835/600/400",
  },
  {
    id: 23,
    name: "Mushroom Risotto",
    price: 675,
    description: "Creamy risotto cooked with a mix of wild mushrooms, Parmesan cheese, and white wine. Contains dairy. Can be made vegan upon request.",
    image: "https://picsum.photos/id/292/600/400",
  },
  {
    id: 24,
    name: "Almond Croissant",
    price: 250,
    description: "A flaky, buttery croissant filled with a sweet almond paste and topped with sliced almonds and powdered sugar. Contains gluten, dairy, and nuts.",
    image: "https://picsum.photos/id/326/600/400",
  },
  {
    id: 25,
    name: "Butter Chicken",
    price: 550,
    description: "Tender chicken in a mildly spiced, creamy tomato sauce. Served with basmati rice and naan bread. Contains dairy and gluten (naan).",
    image: "https://picsum.photos/id/962/600/400",
  },
  {
    id: 26,
    name: "Sushi Platter",
    price: 1200,
    description: "A selection of fresh nigiri and maki rolls, including tuna, salmon, and California rolls. Served with soy sauce, wasabi, and pickled ginger. Contains fish and soy.",
    image: "https://picsum.photos/id/30/600/400",
  },
  {
    id: 27,
    name: "Ribeye Steak",
    price: 1500,
    description: "A 12oz ribeye steak cooked to your liking, served with garlic mashed potatoes and seasonal vegetables. Gluten-free.",
    image: "https://picsum.photos/id/83/600/400",
  },
  {
    id: 28,
    name: "Chocolate Lava Cake",
    price: 375,
    description: "Warm chocolate cake with a gooey molten center, served with a scoop of vanilla bean ice cream. Contains gluten and dairy.",
    image: "https://picsum.photos/id/211/600/400",
  },
  {
    id: 29,
    name: "Chicken Tikka Masala",
    price: 525,
    description: "Chunks of roasted marinated chicken in a spiced curry sauce. The sauce is usually creamy and orange-coloured. Contains dairy.",
    image: "https://picsum.photos/id/992/600/400",
  },
  {
    id: 30,
    name: "Paneer Butter Masala",
    price: 475,
    description: "A rich and creamy dish of paneer (Indian cheese) in a tomato, butter and cashew sauce. Vegetarian. Contains dairy and nuts.",
    image: "https://picsum.photos/id/1060/600/400",
  },
  {
    id: 31,
    name: "Vegetable Samosas",
    price: 180,
    description: "Crispy pastry filled with spiced potatoes and peas, served with a tamarind chutney. Vegan. Contains gluten.",
    image: "https://picsum.photos/id/493/600/400",
  },
  {
    id: 32,
    name: "Garlic Naan",
    price: 90,
    description: "Soft, leavened flatbread baked in a tandoor oven and brushed with garlic butter. Vegetarian. Contains gluten and dairy.",
    image: "https://picsum.photos/id/450/600/400",
  },
  {
    id: 33,
    name: "Classic Margherita Pizza",
    price: 499,
    description: "Traditional pizza with San Marzano tomatoes, fresh mozzarella, basil, salt, and extra-virgin olive oil. Contains gluten and dairy.",
    image: "https://picsum.photos/id/42/600/400",
  },
  {
    id: 34,
    name: "Grilled Salmon Salad",
    price: 899,
    description: "A healthy salad with grilled salmon, mixed greens, cherry tomatoes, and a lemon-dill vinaigrette. Naturally gluten-free.",
    image: "https://picsum.photos/id/338/600/400",
  },
  {
    id: 35,
    name: "Spaghetti Carbonara",
    price: 650,
    description: "A classic Roman pasta dish with egg, pecorino cheese, guanciale (cured pork jowl), and black pepper. Contains gluten, dairy, and pork.",
    image: "https://picsum.photos/id/202/600/400",
  },
  {
    id: 36,
    name: "Vegan Lentil Soup",
    price: 350,
    description: "A hearty and nutritious soup made with green lentils, carrots, celery, and onions. Completely plant-based and gluten-free.",
    image: "https://picsum.photos/id/206/600/400",
  },
  {
    id: 37,
    name: "Chicken Pad Thai",
    price: 575,
    description: "Stir-fried rice noodles with chicken, tofu, peanuts, scrambled egg, and bean sprouts in a tamarind sauce. Contains nuts, egg, and soy.",
    image: "https://picsum.photos/id/24/600/400",
  },
  {
    id: 38,
    name: "Beef Burger",
    price: 550,
    description: "Juicy beef patty on a brioche bun with lettuce, tomato, and our special sauce. Served with fries. Contains gluten and dairy (in bun and sauce).",
    image: "https://picsum.photos/id/835/600/400",
  },
  {
    id: 39,
    name: "Mushroom Risotto",
    price: 675,
    description: "Creamy risotto cooked with a mix of wild mushrooms, Parmesan cheese, and white wine. Contains dairy. Can be made vegan upon request.",
    image: "https://picsum.photos/id/292/600/400",
  },
  {
    id: 40,
    name: "Almond Croissant",
    price: 250,
    description: "A flaky, buttery croissant filled with a sweet almond paste and topped with sliced almonds and powdered sugar. Contains gluten, dairy, and nuts.",
    image: "https://picsum.photos/id/326/600/400",
  },
  {
    id: 41,
    name: "Butter Chicken",
    price: 550,
    description: "Tender chicken in a mildly spiced, creamy tomato sauce. Served with basmati rice and naan bread. Contains dairy and gluten (naan).",
    image: "https://picsum.photos/id/962/600/400",
  },
  {
    id: 42,
    name: "Sushi Platter",
    price: 1200,
    description: "A selection of fresh nigiri and maki rolls, including tuna, salmon, and California rolls. Served with soy sauce, wasabi, and pickled ginger. Contains fish and soy.",
    image: "https://picsum.photos/id/30/600/400",
  },
  {
    id: 43,
    name: "Ribeye Steak",
    price: 1500,
    description: "A 12oz ribeye steak cooked to your liking, served with garlic mashed potatoes and seasonal vegetables. Gluten-free.",
    image: "https://picsum.photos/id/83/600/400",
  },
  {
    id: 44,
    name: "Chocolate Lava Cake",
    price: 375,
    description: "Warm chocolate cake with a gooey molten center, served with a scoop of vanilla bean ice cream. Contains gluten and dairy.",
    image: "https://picsum.photos/id/211/600/400",
  },
  {
    id: 45,
    name: "Chicken Tikka Masala",
    price: 525,
    description: "Chunks of roasted marinated chicken in a spiced curry sauce. The sauce is usually creamy and orange-coloured. Contains dairy.",
    image: "https://picsum.photos/id/992/600/400",
  },
  {
    id: 46,
    name: "Paneer Butter Masala",
    price: 475,
    description: "A rich and creamy dish of paneer (Indian cheese) in a tomato, butter and cashew sauce. Vegetarian. Contains dairy and nuts.",
    image: "https://picsum.photos/id/1060/600/400",
  },
  {
    id: 47,
    name: "Vegetable Samosas",
    price: 180,
    description: "Crispy pastry filled with spiced potatoes and peas, served with a tamarind chutney. Vegan. Contains gluten.",
    image: "https://picsum.photos/id/493/600/400",
  },
  {
    id: 48,
    name: "Garlic Naan",
    price: 90,
    description: "Soft, leavened flatbread baked in a tandoor oven and brushed with garlic butter. Vegetarian. Contains gluten and dairy.",
    image: "https://picsum.photos/id/450/600/400",
  },
  {
    id: 49,
    name: "Classic Margherita Pizza",
    price: 499,
    description: "Traditional pizza with San Marzano tomatoes, fresh mozzarella, basil, salt, and extra-virgin olive oil. Contains gluten and dairy.",
    image: "https://picsum.photos/id/42/600/400",
  },
  {
    id: 50,
    name: "Grilled Salmon Salad",
    price: 899,
    description: "A healthy salad with grilled salmon, mixed greens, cherry tomatoes, and a lemon-dill vinaigrette. Naturally gluten-free.",
    image: "https://picsum.photos/id/338/600/400",
  },
  {
    id: 51,
    name: "Spaghetti Carbonara",
    price: 650,
    description: "A classic Roman pasta dish with egg, pecorino cheese, guanciale (cured pork jowl), and black pepper. Contains gluten, dairy, and pork.",
    image: "https://picsum.photos/id/202/600/400",
  },
  {
    id: 52,
    name: "Vegan Lentil Soup",
    price: 350,
    description: "A hearty and nutritious soup made with green lentils, carrots, celery, and onions. Completely plant-based and gluten-free.",
    image: "https://picsum.photos/id/206/600/400",
  },
  {
    id: 53,
    name: "Chicken Pad Thai",
    price: 575,
    description: "Stir-fried rice noodles with chicken, tofu, peanuts, scrambled egg, and bean sprouts in a tamarind sauce. Contains nuts, egg, and soy.",
    image: "https://picsum.photos/id/24/600/400",
  },
  {
    id: 54,
    name: "Beef Burger",
    price: 550,
    description: "Juicy beef patty on a brioche bun with lettuce, tomato, and our special sauce. Served with fries. Contains gluten and dairy (in bun and sauce).",
    image: "https://picsum.photos/id/835/600/400",
  },
  {
    id: 55,
    name: "Mushroom Risotto",
    price: 675,
    description: "Creamy risotto cooked with a mix of wild mushrooms, Parmesan cheese, and white wine. Contains dairy. Can be made vegan upon request.",
    image: "https://picsum.photos/id/292/600/400",
  },
  {
    id: 56,
    name: "Almond Croissant",
    price: 250,
    description: "A flaky, buttery croissant filled with a sweet almond paste and topped with sliced almonds and powdered sugar. Contains gluten, dairy, and nuts.",
    image: "https://picsum.photos/id/326/600/400",
  },
  {
    id: 57,
    name: "Butter Chicken",
    price: 550,
    description: "Tender chicken in a mildly spiced, creamy tomato sauce. Served with basmati rice and naan bread. Contains dairy and gluten (naan).",
    image: "https://picsum.photos/id/962/600/400",
  },
  {
    id: 58,
    name: "Sushi Platter",
    price: 1200,
    description: "A selection of fresh nigiri and maki rolls, including tuna, salmon, and California rolls. Served with soy sauce, wasabi, and pickled ginger. Contains fish and soy.",
    image: "https://picsum.photos/id/30/600/400",
  },
  {
    id: 59,
    name: "Ribeye Steak",
    price: 1500,
    description: "A 12oz ribeye steak cooked to your liking, served with garlic mashed potatoes and seasonal vegetables. Gluten-free.",
    image: "https://picsum.photos/id/83/600/400",
  },
  {
    id: 60,
    name: "Chocolate Lava Cake",
    price: 375,
    description: "Warm chocolate cake with a gooey molten center, served with a scoop of vanilla bean ice cream. Contains gluten and dairy.",
    image: "https://picsum.photos/id/211/600/400",
  },
  {
    id: 61,
    name: "Chicken Tikka Masala",
    price: 525,
    description: "Chunks of roasted marinated chicken in a spiced curry sauce. The sauce is usually creamy and orange-coloured. Contains dairy.",
    image: "https://picsum.photos/id/992/600/400",
  },
  {
    id: 62,
    name: "Paneer Butter Masala",
    price: 475,
    description: "A rich and creamy dish of paneer (Indian cheese) in a tomato, butter and cashew sauce. Vegetarian. Contains dairy and nuts.",
    image: "https://picsum.photos/id/1060/600/400",
  },
  {
    id: 63,
    name: "Vegetable Samosas",
    price: 180,
    description: "Crispy pastry filled with spiced potatoes and peas, served with a tamarind chutney. Vegan. Contains gluten.",
    image: "https://picsum.photos/id/493/600/400",
  },
  {
    id: 64,
    name: "Garlic Naan",
    price: 90,
    description: "Soft, leavened flatbread baked in a tandoor oven and brushed with garlic butter. Vegetarian. Contains gluten and dairy.",
    image: "https://picsum.photos/id/450/600/400",
  },
  {
    id: 65,
    name: "Classic Margherita Pizza",
    price: 499,
    description: "Traditional pizza with San Marzano tomatoes, fresh mozzarella, basil, salt, and extra-virgin olive oil. Contains gluten and dairy.",
    image: "https://picsum.photos/id/42/600/400",
  },
  {
    id: 66,
    name: "Grilled Salmon Salad",
    price: 899,
    description: "A healthy salad with grilled salmon, mixed greens, cherry tomatoes, and a lemon-dill vinaigrette. Naturally gluten-free.",
    image: "https://picsum.photos/id/338/600/400",
  },
  {
    id: 67,
    name: "Spaghetti Carbonara",
    price: 650,
    description: "A classic Roman pasta dish with egg, pecorino cheese, guanciale (cured pork jowl), and black pepper. Contains gluten, dairy, and pork.",
    image: "https://picsum.photos/id/202/600/400",
  },
  {
    id: 68,
    name: "Vegan Lentil Soup",
    price: 350,
    description: "A hearty and nutritious soup made with green lentils, carrots, celery, and onions. Completely plant-based and gluten-free.",
    image: "https://picsum.photos/id/206/600/400",
  },
  {
    id: 69,
    name: "Chicken Pad Thai",
    price: 575,
    description: "Stir-fried rice noodles with chicken, tofu, peanuts, scrambled egg, and bean sprouts in a tamarind sauce. Contains nuts, egg, and soy.",
    image: "https://picsum.photos/id/24/600/400",
  },
  {
    id: 70,
    name: "Beef Burger",
    price: 550,
    description: "Juicy beef patty on a brioche bun with lettuce, tomato, and our special sauce. Served with fries. Contains gluten and dairy (in bun and sauce).",
    image: "https://picsum.photos/id/835/600/400",
  },
  {
    id: 71,
    name: "Mushroom Risotto",
    price: 675,
    description: "Creamy risotto cooked with a mix of wild mushrooms, Parmesan cheese, and white wine. Contains dairy. Can be made vegan upon request.",
    image: "https://picsum.photos/id/292/600/400",
  },
  {
    id: 72,
    name: "Almond Croissant",
    price: 250,
    description: "A flaky, buttery croissant filled with a sweet almond paste and topped with sliced almonds and powdered sugar. Contains gluten, dairy, and nuts.",
    image: "https://picsum.photos/id/326/600/400",
  },
  {
    id: 73,
    name: "Butter Chicken",
    price: 550,
    description: "Tender chicken in a mildly spiced, creamy tomato sauce. Served with basmati rice and naan bread. Contains dairy and gluten (naan).",
    image: "https://picsum.photos/id/962/600/400",
  },
  {
    id: 74,
    name: "Sushi Platter",
    price: 1200,
    description: "A selection of fresh nigiri and maki rolls, including tuna, salmon, and California rolls. Served with soy sauce, wasabi, and pickled ginger. Contains fish and soy.",
    image: "https://picsum.photos/id/30/600/400",
  },
  {
    id: 75,
    name: "Ribeye Steak",
    price: 1500,
    description: "A 12oz ribeye steak cooked to your liking, served with garlic mashed potatoes and seasonal vegetables. Gluten-free.",
    image: "https://picsum.photos/id/83/600/400",
  },
];
