import type { Dish } from "@/types";

export const initialDishes: Dish[] = [
  {
    id: 1,
    name: "Classic Margherita Pizza",
    price: 18.5,
    description: "Traditional pizza with San Marzano tomatoes, fresh mozzarella, basil, salt, and extra-virgin olive oil. Contains gluten and dairy.",
    image: "https://picsum.photos/600/400?random=1",
  },
  {
    id: 2,
    name: "Grilled Salmon Salad",
    price: 22.0,
    description: "A healthy salad with grilled salmon, mixed greens, cherry tomatoes, and a lemon-dill vinaigrette. Naturally gluten-free.",
    image: "https://picsum.photos/600/400?random=2",
  },
  {
    id: 3,
    name: "Spaghetti Carbonara",
    price: 20.0,
    description: "A classic Roman pasta dish with egg, pecorino cheese, guanciale (cured pork jowl), and black pepper. Contains gluten, dairy, and pork.",
    image: "https://picsum.photos/600/400?random=3",
  },
  {
    id: 4,
    name: "Vegan Lentil Soup",
    price: 12.0,
    description: "A hearty and nutritious soup made with green lentils, carrots, celery, and onions. Completely plant-based and gluten-free.",
    image: "https://picsum.photos/600/400?random=4",
  },
  {
    id: 5,
    name: "Chicken Pad Thai",
    price: 19.5,
    description: "Stir-fried rice noodles with chicken, tofu, peanuts, scrambled egg, and bean sprouts in a tamarind sauce. Contains nuts, egg, and soy.",
    image: "https://picsum.photos/600/400?random=5",
  },
  {
    id: 6,
    name: "Beef Burger",
    price: 17.0,
    description: "Juicy beef patty on a brioche bun with lettuce, tomato, and our special sauce. Served with fries. Contains gluten and dairy (in bun and sauce).",
    image: "https://picsum.photos/600/400?random=6",
  },
  {
    id: 7,
    name: "Mushroom Risotto",
    price: 21.0,
    description: "Creamy risotto cooked with a mix of wild mushrooms, Parmesan cheese, and white wine. Contains dairy. Can be made vegan upon request.",
    image: "https://picsum.photos/600/400?random=7",
  },
  {
    id: 8,
    name: "Almond Croissant",
    price: 6.5,
    description: "A flaky, buttery croissant filled with a sweet almond paste and topped with sliced almonds and powdered sugar. Contains gluten, dairy, and nuts.",
    image: "https://picsum.photos/600/400?random=8",
  },
  {
    id: 9,
    name: "Butter Chicken",
    price: 23.0,
    description: "Tender chicken in a mildly spiced, creamy tomato sauce. Served with basmati rice and naan bread. Contains dairy and gluten (naan).",
    image: "https://picsum.photos/600/400?random=9",
  },
  {
    id: 10,
    name: "Sushi Platter",
    price: 28.0,
    description: "A selection of fresh nigiri and maki rolls, including tuna, salmon, and California rolls. Served with soy sauce, wasabi, and pickled ginger. Contains fish and soy.",
    image: "https://picsum.photos/600/400?random=10",
  },
  {
    id: 11,
    name: "Ribeye Steak",
    price: 35.0,
    description: "A 12oz ribeye steak cooked to your liking, served with garlic mashed potatoes and seasonal vegetables. Gluten-free.",
    image: "https://picsum.photos/600/400?random=11",
  },
  {
    id: 12,
    name: "Chocolate Lava Cake",
    price: 11.0,
    description: "Warm chocolate cake with a gooey molten center, served with a scoop of vanilla bean ice cream. Contains gluten and dairy.",
    image: "https://picsum.photos/600/400?random=12",
  },
  {
    id: 13,
    name: "Chicken Tikka Masala",
    price: 22.5,
    description: "Chunks of roasted marinated chicken in a spiced curry sauce. The sauce is usually creamy and orange-coloured. Contains dairy.",
    image: "https://picsum.photos/600/400?random=13",
  },
  {
    id: 14,
    name: "Paneer Butter Masala",
    price: 20.5,
    description: "A rich and creamy dish of paneer (Indian cheese) in a tomato, butter and cashew sauce. Vegetarian. Contains dairy and nuts.",
    image: "https://picsum.photos/600/400?random=14",
  },
  {
    id: 15,
    name: "Vegetable Samosas",
    price: 9.0,
    description: "Crispy pastry filled with spiced potatoes and peas, served with a tamarind chutney. Vegan. Contains gluten.",
    image: "https://picsum.photos/600/400?random=15",
  },
  {
    id: 16,
    name: "Garlic Naan",
    price: 5.0,
    description: "Soft, leavened flatbread baked in a tandoor oven and brushed with garlic butter. Vegetarian. Contains gluten and dairy.",
    image: "https://picsum.photos/600/400?random=16",
  },
];
